export const EQ = 2 // 等于
export const NE = 3 // 不等于
export const ALL = 1 // 同时包含
export const NIN = 11 // 数组不包含
export const LK = 12 // 字符串包含
export const ULK = 13 // 字符串不包含
export const EP = 16 // 为空
export const NEP = 17 // 不为空
export const GT = 4 // 大于
export const GTE = 5 // 大于等于
export const LT = 6 // 小于
export const LTE = 7 // 小于等于
export const RG = 8 // 选择范围
export const IN_MANY = 0 // 包含任意一个
export const IN_ONE = 10 // 等于任意一个
export const ALL_ADDR = 14 // 属于
export const NIN_ADDR = 15 // 不属于，地址不属于
// export const VF = 'verified' // 已验证
// export const NVF = 'unverified' // 未验证
// export const FM = 9 // formula 动态筛选
// export const LO = // link_to 选择
