export const formData = {
  fields: [
    {
      clearable: true,
      visibility: true,
      editable: true,
      format: 'yyyy-MM-dd',
      typeName: '日期时间',
      'value-format': 'yyyy-MM-dd',
      description: '',
      type: 'date',
      readonly: false,
      style: {
        width: '254px',
        maxWidth: '100%',
      },
      typeId: 'DATE',
      conditionType: 2,
      placeholder: '请选择实际送货日期',
      config: {
        label: '实际送货日期',
        defaultValueSource: {
          id: '',
          type: 0,
        },
        required: true,
        showLabel: true,
        renderKey: 'KknDhEB1678166837506',
        layout: 'colFormItem',
        displayType: true,
        showDefaultValue: true,
        tagIcon: 'date',
        changeTag: true,
        tag: 'el-date-picker',
        defaultValueType: 0,
        span: 6,
      },
      vModel: 'fieldKknDhEB1678166837506',
    },
    {
      visibility: true,
      editable: true,
      typeName: '单选按钮组',
      description: '',
      size: 'small',
      readonly: false,
      segment: 'vertical',
      style: {
        display: 'block',
      },
      typeId: 'RADIO',
      conditionType: 3,
      config: {
        border: false,
        defaultValue: '是',
        label: '是否依据订单送货',
        required: true,
        showLabel: true,
        renderKey: 'lXUGSFB1678437737540',
        layout: 'colFormItem',
        optionType: 'default',
        displayType: true,
        showDefaultValue: false,
        tagIcon: 'radio',
        changeTag: true,
        tag: 'el-radio-group',
        span: 6,
      },
      __slot__: {
        options: [
          {
            checked: true,
            label: '是',
            value: 1,
          },
          {
            checked: false,
            label: '否',
            value: 2,
          },
        ],
      },
      vModel: 'fieldlXUGSFB1678437737540',
    },
    {
      visibility: true,
      editable: true,
      typeName: '单选按钮组',
      description: '',
      size: 'small',
      readonly: false,
      segment: 'vertical',
      style: {
        display: 'block',
      },
      typeId: 'RADIO',
      conditionType: 3,
      config: {
        border: false,
        defaultValue: '是',
        label: '是否送货本厂',
        required: true,
        showLabel: true,
        renderKey: 'KCTcSFB1678440827065',
        layout: 'colFormItem',
        optionType: 'default',
        displayType: true,
        showDefaultValue: false,
        tagIcon: 'radio',
        changeTag: true,
        tag: 'el-radio-group',
        span: 6,
      },
      __slot__: {
        options: [
          {
            checked: true,
            label: '是',
            value: 1,
          },
          {
            checked: false,
            label: '否',
            value: 2,
          },
        ],
      },
      vModel: 'fieldKCTcSFB1678440827065',
    },
    {
      linkedFillRules: [
        {
          visible: 1,
          depend: {
            field: 'fieldYgHKSFB167843826480601',
          },
          check: true,
          label: '编号',
          type: 0,
          parentId: 1,
          foreignId: 0,
          childrenFlag: 0,
          name: 'fieldsQLGSFB1678438134927',
          typeId: 'INPUT',
          id: '1634114142449610754',
          vModel: 'fieldsQLGSFB1678438134927',
        },
      ],
      visibility: true,
      editable: true,
      typeName: '关联数据',
      description: '',
      linkList: [
        {
          visible: 1,
          label: '编号',
          type: 0,
          parentId: 1,
          foreignId: 0,
          childrenFlag: 0,
          name: 'fieldsQLGSFB1678438134927',
          typeId: 'INPUT',
          id: '1634114142449610754',
          vModel: 'fieldsQLGSFB1678438134927',
        },
      ],
      readonly: false,
      showTitle: false,
      style: {
        width: '100%',
        maxWidth: '100%',
      },
      typeId: 'LINKED_DATA',
      filterCond: [],
      config: {
        dbTable: '1634114142348947457',
        label: '勾选到货合同号',
        required: false,
        showLabel: true,
        renderKey: 'kgPHSFB1678437864676',
        layout: 'colFormItem',
        dbFieldList: ['1634114142449610754'],
        displayType: true,
        showDefaultValue: false,
        tagIcon: 'input',
        changeTag: true,
        tag: 'my-form',
        span: 6,
      },
      linkedShowField: [],
      vModel: 'fieldkgPHSFB1678437864676',
    },
    {
      visibility: true,
      editable: false,
      typeName: '单行文本',
      description: '',
      limitRepeat: false,
      repeatReminderText: '此项内容已存在，不允许重复提交',
      readonly: false,
      linkVModel: 'fieldkgPHSFB1678437864676',
      style: {
        width: '254px',
        maxWidth: '100%',
      },
      typeId: 'INPUT',
      placeholder: '请输入到货合同号',
      config: {
        defaultValue: '',
        typeOption: [
          {
            label: '无',
            value: 'text',
          },
          {
            label: '手机号码',
            value: 'phoneNumber',
          },
          {
            label: '电话号码',
            value: 'tel',
          },
          {
            label: '邮政编码',
            value: 'zipCode',
          },
          {
            label: '身份证号码',
            value: 'idNumber',
          },
          {
            label: '邮箱',
            value: 'email',
          },
        ],
        format: 'text',
        label: '到货合同号',
        defaultValueSource: {
          id: '',
          type: 0,
        },
        required: true,
        showLabel: true,
        renderKey: 'sQLGSFB1678438134927',
        layout: 'colFormItem',
        displayType: true,
        tagIcon: 'input',
        changeTag: true,
        tag: 'el-input',
        defaultValueType: 0,
        span: 6,
      },
      vModel: 'fieldYgHKSFB167843826480601',
    },
    {
      linkedFillRules: [
        {
          visible: 1,
          depend: {
            field: 'fieldQmWKSFB167843830585501',
          },
          check: true,
          label: '编号',
          type: 0,
          parentId: 1,
          foreignId: 0,
          childrenFlag: 0,
          name: 'fieldsQLGSFB1678438134927',
          typeId: 'INPUT',
          id: '1634114142449610754',
          vModel: 'fieldsQLGSFB1678438134927',
        },
      ],
      visibility: true,
      editable: true,
      typeName: '关联数据',
      description: '',
      linkList: [],
      readonly: false,
      showTitle: true,
      style: {
        width: '100%',
        maxWidth: '100%',
      },
      typeId: 'LINKED_DATA',
      filterCond: [],
      config: {
        dbTable: '1634114142348947457',
        label: '勾选送货单号',
        required: false,
        showLabel: true,
        renderKey: 'SlqGSFB1678438219215',
        layout: 'colFormItem',
        dbFieldList: ['1632936901233516546'],
        displayType: true,
        showDefaultValue: false,
        tagIcon: 'input',
        changeTag: true,
        tag: 'my-form',
        span: 6,
      },
      linkedShowField: [],
      vModel: 'fieldSlqGSFB1678438219215',
    },
    {
      visibility: true,
      editable: false,
      typeName: '单行文本',
      description: '',
      limitRepeat: false,
      repeatReminderText: '此项内容已存在，不允许重复提交',
      readonly: false,
      linkVModel: 'fieldSlqGSFB1678438219215',
      style: {
        width: '254px',
        maxWidth: '100%',
      },
      typeId: 'INPUT',
      placeholder: '请输入送货单号',
      config: {
        defaultValue: '',
        typeOption: [
          {
            label: '无',
            value: 'text',
          },
          {
            label: '手机号码',
            value: 'phoneNumber',
          },
          {
            label: '电话号码',
            value: 'tel',
          },
          {
            label: '邮政编码',
            value: 'zipCode',
          },
          {
            label: '身份证号码',
            value: 'idNumber',
          },
          {
            label: '邮箱',
            value: 'email',
          },
        ],
        format: 'text',
        label: '送货单号',
        defaultValueSource: {
          id: '',
          type: 0,
        },
        required: true,
        showLabel: true,
        renderKey: 'sQLGSFB1678438134927',
        layout: 'colFormItem',
        displayType: true,
        tagIcon: 'input',
        changeTag: true,
        tag: 'el-input',
        defaultValueType: 0,
        span: 6,
      },
      vModel: 'fieldQmWKSFB167843830585501',
    },
    {
      linkedFillRules: [
        {
          visible: 1,
          depend: {
            field: 'fielddVdMSFB167843860511801',
          },
          check: true,
          label: '编号',
          type: 0,
          parentId: 1,
          foreignId: 0,
          childrenFlag: 0,
          name: 'fieldsQLGSFB1678438134927',
          typeId: 'INPUT',
          id: '1634114142449610754',
          vModel: 'fieldsQLGSFB1678438134927',
        },
      ],
      visibility: true,
      editable: true,
      typeName: '关联数据',
      description: '',
      linkList: [],
      readonly: false,
      showTitle: true,
      style: {
        width: '100%',
        maxWidth: '100%',
      },
      typeId: 'LINKED_DATA',
      filterCond: [],
      config: {
        dbTable: '1634114142348947457',
        label: '勾选船号',
        required: false,
        showLabel: true,
        renderKey: 'BFsLSFB1678438503850',
        layout: 'colFormItem',
        dbFieldList: ['1632936901233516546'],
        displayType: true,
        showDefaultValue: false,
        tagIcon: 'input',
        changeTag: true,
        tag: 'my-form',
        span: 6,
      },
      linkedShowField: [],
      vModel: 'fieldBFsLSFB1678438503850',
    },
    {
      visibility: true,
      editable: false,
      typeName: '单行文本',
      description: '',
      limitRepeat: false,
      repeatReminderText: '此项内容已存在，不允许重复提交',
      readonly: false,
      linkVModel: 'fieldBFsLSFB1678438503850',
      style: {
        width: '254px',
        maxWidth: '100%',
      },
      typeId: 'INPUT',
      placeholder: '请输入船号',
      config: {
        defaultValue: '',
        typeOption: [
          {
            label: '无',
            value: 'text',
          },
          {
            label: '手机号码',
            value: 'phoneNumber',
          },
          {
            label: '电话号码',
            value: 'tel',
          },
          {
            label: '邮政编码',
            value: 'zipCode',
          },
          {
            label: '身份证号码',
            value: 'idNumber',
          },
          {
            label: '邮箱',
            value: 'email',
          },
        ],
        format: 'text',
        label: '船号',
        defaultValueSource: {
          id: '',
          type: 0,
        },
        required: true,
        showLabel: true,
        renderKey: 'sQLGSFB1678438134927',
        layout: 'colFormItem',
        displayType: true,
        tagIcon: 'input',
        changeTag: true,
        tag: 'el-input',
        defaultValueType: 0,
        span: 6,
      },
      vModel: 'fielddVdMSFB167843860511801',
    },
    {
      notChild: true,
      fieldDisplayRules: [],
      visibility: true,
      editable: true,
      typeName: '子表单',
      description: '',
      readonly: false,
      children: [
        {
          linkedFillRules: [
            {
              visible: 1,
              depend: {
                field: 'fieldKMhNSFB167843875651801',
              },
              check: true,
              label: '编号',
              type: 0,
              parentId: 1,
              foreignId: 0,
              childrenFlag: 0,
              name: 'fieldsQLGSFB1678438134927',
              typeId: 'INPUT',
              id: '1634114142449610754',
              vModel: 'fieldsQLGSFB1678438134927',
            },
          ],
          visibility: true,
          editable: true,
          typeName: '关联数据',
          description: '',
          linkList: [],
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          showTitle: false,
          style: {
            width: '100%',
            maxWidth: '100%',
          },
          typeId: 'LINKED_DATA',
          filterCond: [],
          config: {
            dbTable: '1634114142348947457',
            label: '勾选工程号',
            required: false,
            showLabel: true,
            renderKey: 'miyDhEB1678166867066',
            layout: 'colFormItem',
            dbFieldList: ['1632936901233516546', '1632936901237710850'],
            displayType: true,
            showDefaultValue: false,
            tagIcon: 'input',
            changeTag: true,
            tag: 'my-form',
            span: 24,
          },
          linkedShowField: [],
          vModel: 'fieldmiyDhEB1678166867066',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          linkVModel: 'fieldmiyDhEB1678166867066',
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入工程号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '工程号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: true,
            showLabel: true,
            renderKey: 'sQLGSFB1678438134927',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldKMhNSFB167843875651801',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入技术采购单号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '技术采购单号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'gAgOSFB1678438901921',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldgAgOSFB1678438901921',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入采购单号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '采购单号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: true,
            showLabel: true,
            renderKey: 'ecpOSFB1678438918981',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldecpOSFB1678438918981',
        },
        {
          visibility: true,
          editable: false,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入合同号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '合同号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'ygrOSFB1678438925179',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldygrOSFB1678438925179',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入物资编码',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '物资编码',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: true,
            showLabel: true,
            renderKey: 'GzKPSFB1678438977514',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldGzKPSFB1678438977514',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入物资描述',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '物资描述',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'WvXPSFB1678439011906',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldWvXPSFB1678439011906',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入物资规格',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '物资规格',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'pIYPSFB1678439012491',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldpIYPSFB1678439012491',
        },
        {
          visibility: true,
          editable: false,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入管理单位',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '管理单位',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'gEYPSFB1678439012707',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldgEYPSFB1678439012707',
        },
        {
          visibility: true,
          editable: false,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入计价单位',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '计价单位',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'aCYPSFB1678439012897',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldaCYPSFB1678439012897',
        },
        {
          'step-strictly': false,
          controls: false,
          visibility: true,
          editable: true,
          precision: 0,
          typeName: '数字',
          description: '',
          'controls-position': '',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          step: 1,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'NUMBER_INPUT',
          conditionType: 1,
          placeholder: '请输入送货管理数量',
          config: {
            typeOption: [
              {
                label: '数值',
                value: 1,
              },
              {
                label: '百分比',
                value: 2,
              },
            ],
            format: 1,
            showThousandsSeparator: false,
            label: '送货管理数量',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: true,
            showLabel: true,
            renderKey: 'FkSQSFB1678439138948',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'number',
            changeTag: true,
            tag: 'el-input-number',
            showDecimal: false,
            defaultValueType: 0,
            limitRange: false,
            span: 6,
          },
          vModel: 'fieldFkSQSFB1678439138948',
        },
        {
          'step-strictly': false,
          controls: false,
          visibility: true,
          editable: false,
          precision: 0,
          typeName: '数字',
          description: '',
          'controls-position': '',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          step: 1,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'NUMBER_INPUT',
          conditionType: 1,
          placeholder: '请输入送货计价数量',
          config: {
            typeOption: [
              {
                label: '数值',
                value: 1,
              },
              {
                label: '百分比',
                value: 2,
              },
            ],
            format: 1,
            showThousandsSeparator: false,
            label: '送货计价数量',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'ssfQSFB1678439174063',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'number',
            changeTag: true,
            tag: 'el-input-number',
            showDecimal: false,
            defaultValueType: 0,
            limitRange: false,
            span: 6,
          },
          vModel: 'fieldssfQSFB1678439174063',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入炉批号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '炉批号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'rCYPSFB1678439013073',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldrCYPSFB1678439013073',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入批号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '批号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'PyBRSFB1678439234351',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldPyBRSFB1678439234351',
        },
        {
          clearable: true,
          visibility: true,
          editable: true,
          format: 'yyyy-MM-dd',
          typeName: '日期时间',
          'value-format': 'yyyy-MM-dd',
          description: '',
          type: 'date',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'DATE',
          conditionType: 2,
          placeholder: '请选择生产日期',
          config: {
            label: '生产日期',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'cuHRSFB1678439250186',
            layout: 'colFormItem',
            displayType: true,
            showDefaultValue: true,
            tagIcon: 'date',
            changeTag: true,
            tag: 'el-date-picker',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldcuHRSFB1678439250186',
        },
        {
          'step-strictly': false,
          controls: false,
          visibility: true,
          editable: true,
          precision: 0,
          typeName: '数字',
          description: '',
          'controls-position': '',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          step: 1,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'NUMBER_INPUT',
          conditionType: 1,
          placeholder: '请输入保质期天数',
          config: {
            typeOption: [
              {
                label: '数值',
                value: 1,
              },
              {
                label: '百分比',
                value: 2,
              },
            ],
            format: 1,
            showThousandsSeparator: false,
            label: '保质期天数',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'yPQRSFB1678439272553',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'number',
            changeTag: true,
            tag: 'el-input-number',
            showDecimal: false,
            defaultValueType: 0,
            limitRange: false,
            span: 6,
          },
          vModel: 'fieldyPQRSFB1678439272553',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入包装规格',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '包装规格',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'mNYPSFB1678439013273',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldmNYPSFB1678439013273',
        },
        {
          visibility: true,
          editable: false,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入来船名/车牌号*',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '来船名/车牌号*',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'cXYPSFB1678439013433',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldcXYPSFB1678439013433',
        },
        {
          visibility: true,
          editable: false,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入生产厂商',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '生产厂商',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'NYYPSFB1678439013618',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldNYYPSFB1678439013618',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入备注',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '备注',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'moZSSFB1678439438746',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldmoZSSFB1678439438746',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入条形码',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '条形码',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'vDkSSFB1678439466498',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldvDkSSFB1678439466498',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入零件号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '零件号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'CwsSSFB1678439490386',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldCwsSSFB1678439490386',
        },
        {
          'step-strictly': false,
          controls: false,
          visibility: true,
          editable: true,
          precision: 0,
          typeName: '数字',
          description: '',
          'controls-position': '',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          step: 1,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'NUMBER_INPUT',
          conditionType: 1,
          placeholder: '请输入单价',
          config: {
            typeOption: [
              {
                label: '数值',
                value: 1,
              },
              {
                label: '百分比',
                value: 2,
              },
            ],
            format: 1,
            showThousandsSeparator: false,
            label: '单价',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'KDZTSFB1678439577508',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'number',
            changeTag: true,
            tag: 'el-input-number',
            showDecimal: false,
            defaultValueType: 0,
            limitRange: false,
            span: 6,
          },
          vModel: 'fieldKDZTSFB1678439577508',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入生产托盘号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '生产托盘号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'IDgTSFB1678439596204',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldIDgTSFB1678439596204',
        },
        {
          'step-strictly': false,
          controls: false,
          visibility: true,
          editable: true,
          precision: 0,
          typeName: '数字',
          description: '',
          'controls-position': '',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          step: 1,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'NUMBER_INPUT',
          conditionType: 1,
          placeholder: '请输入已送货数量',
          config: {
            typeOption: [
              {
                label: '数值',
                value: 1,
              },
              {
                label: '百分比',
                value: 2,
              },
            ],
            format: 1,
            showThousandsSeparator: false,
            label: '已送货数量',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'HItTSFB1678439632289',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'number',
            changeTag: true,
            tag: 'el-input-number',
            showDecimal: false,
            defaultValueType: 0,
            limitRange: false,
            span: 6,
          },
          vModel: 'fieldHItTSFB1678439632289',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入名称',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '名称',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'OVFUSFB1678439665509',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldOVFUSFB1678439665509',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入图号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '图号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'XgKUSFB1678439679788',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldXgKUSFB1678439679788',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入材质',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '材质',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'FkNUSFB1678439687269',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldFkNUSFB1678439687269',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入规格',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '规格',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'CfQUSFB1678439695284',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldCfQUSFB1678439695284',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入单重',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '单重',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'wNTUSFB1678439702246',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldwNTUSFB1678439702246',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入生产批次',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '生产批次',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'vqWUSFB1678439712061',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldvqWUSFB1678439712061',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入作业部门',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '作业部门',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'COZUSFB1678439719179',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldCOZUSFB1678439719179',
        },
        {
          clearable: true,
          visibility: true,
          editable: true,
          format: 'yyyy-MM-dd',
          typeName: '日期时间',
          'value-format': 'yyyy-MM-dd',
          description: '',
          type: 'date',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'DATE',
          conditionType: 2,
          placeholder: '请选择计划需求日期',
          config: {
            label: '计划需求日期',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'IbkUSFB1678439749381',
            layout: 'colFormItem',
            displayType: true,
            showDefaultValue: true,
            tagIcon: 'date',
            changeTag: true,
            tag: 'el-date-picker',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldIbkUSFB1678439749381',
        },
        {
          'step-strictly': false,
          controls: false,
          visibility: true,
          editable: true,
          precision: 0,
          typeName: '数字',
          description: '',
          'controls-position': '',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          step: 1,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'NUMBER_INPUT',
          conditionType: 1,
          placeholder: '请输入减少数量',
          config: {
            typeOption: [
              {
                label: '数值',
                value: 1,
              },
              {
                label: '百分比',
                value: 2,
              },
            ],
            format: 1,
            showThousandsSeparator: false,
            label: '减少数量',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'TBrUSFB1678439767198',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'number',
            changeTag: true,
            tag: 'el-input-number',
            showDecimal: false,
            defaultValueType: 0,
            limitRange: false,
            span: 6,
          },
          vModel: 'fieldTBrUSFB1678439767198',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '请输入托盘零件号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '托盘零件号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'FDzUSFB1678439789033',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldFDzUSFB1678439789033',
        },
        {
          visibility: true,
          editable: true,
          typeName: '单行文本',
          description: '',
          limitRepeat: false,
          repeatReminderText: '此项内容已存在，不允许重复提交',
          parentKey: 'fieldeCtDhEB1678166852263',
          readonly: false,
          style: {
            width: '254px',
            maxWidth: '100%',
          },
          typeId: 'INPUT',
          placeholder: '输入请请料单号',
          config: {
            defaultValue: '',
            typeOption: [
              {
                label: '无',
                value: 'text',
              },
              {
                label: '手机号码',
                value: 'phoneNumber',
              },
              {
                label: '电话号码',
                value: 'tel',
              },
              {
                label: '邮政编码',
                value: 'zipCode',
              },
              {
                label: '身份证号码',
                value: 'idNumber',
              },
              {
                label: '邮箱',
                value: 'email',
              },
            ],
            format: 'text',
            label: '请料单号',
            defaultValueSource: {
              id: '',
              type: 0,
            },
            required: false,
            showLabel: true,
            renderKey: 'fLGVSFB1678439816341',
            layout: 'colFormItem',
            displayType: true,
            tagIcon: 'input',
            changeTag: true,
            tag: 'el-input',
            defaultValueType: 0,
            span: 6,
          },
          vModel: 'fieldfLGVSFB1678439816341',
        },
      ],
      tableList: [],
      style: {
        width: '254px',
        maxWidth: '100%',
      },
      typeId: 'CHILD_FORM',
      value: [
        {
          fieldXgKUSFB1678439679788: '',
          fieldPyBRSFB1678439234351: '',
          fieldvqWUSFB1678439712061: '',
          fieldmiyDhEB1678166867066: '',
          fieldrCYPSFB1678439013073: '',
          fieldCwsSSFB1678439490386: '',
          fieldFDzUSFB1678439789033: '',
          fieldvDkSSFB1678439466498: '',
          fieldyPQRSFB1678439272553: '',
          fieldcuHRSFB1678439250186: '',
          fieldIDgTSFB1678439596204: '',
          fieldcXYPSFB1678439013433: '',
          fieldpIYPSFB1678439012491: '',
          fieldWvXPSFB1678439011906: '',
          fieldaCYPSFB1678439012897: '',
          fieldKDZTSFB1678439577508: '',
          fieldmoZSSFB1678439438746: '',
          fieldmNYPSFB1678439013273: '',
          fieldygrOSFB1678438925179: '',
          fieldgEYPSFB1678439012707: '',
          fieldTBrUSFB1678439767198: '',
          fieldHItTSFB1678439632289: '',
          fieldCfQUSFB1678439695284: '',
          fieldfLGVSFB1678439816341: '',
          fieldFkNUSFB1678439687269: '',
          fieldNYYPSFB1678439013618: '',
          fieldFkSQSFB1678439138948: '',
          fieldgAgOSFB1678438901921: '',
          fieldwNTUSFB1678439702246: '',
          fieldecpOSFB1678438918981: '',
          fieldKMhNSFB167843875651801: '',
          fieldOVFUSFB1678439665509: '',
          fieldGzKPSFB1678438977514: '',
          fieldCOZUSFB1678439719179: '',
          fieldIbkUSFB1678439749381: '',
          fieldssfQSFB1678439174063: '',
        },
      ],
      config: {
        label: '明细',
        defaultValueSource: {
          id: '',
          type: 0,
        },
        showLabel: true,
        renderKey: 'eCtDhEB1678166852263',
        layout: 'rowFormItem',
        displayType: true,
        showDefaultValue: true,
        tagIcon: 'input',
        showRequired: false,
        changeTag: true,
        tag: 'my-table',
        defaultValueType: 0,
        span: 24,
      },
      __slot__: {
        dataList: [],
      },
      vModel: 'fieldeCtDhEB1678166852263',
    },
  ],
  formConf: {
    dataFilterSetting: {
      cond: [],
      rel: 0,
    },
    description: '',
    disabled: false,
    fieldDisplayRules: [],
    formId: '1632976450517114882',
    formModel: 'formData',
    formRef: 'elForm',
    formRules: 'rules',
    formSubmissionValidation: [],
    frontEndEvents: [],
    labelPosition: 'top',
    labelWidth: 100,
    numberOfColumns: 6,
    size: 'mini',
    submitAssociationOperation: [],
    submitButtonState: 0,
    submitButtonText: '提交',
  },
}

export const formValues = {
  fieldKCTcSFB1678440827065: null,
  createBy: [
    {
      id: '1634027128165412866',
      name: 'admin002',
      typeId: 'MEMBER_RADIO',
      type: 0,
    },
  ],
  fielddVdMSFB167843860511801: '007',
  updateBy: [
    {
      id: '1634027128165412866',
      name: 'admin002',
      typeId: 'MEMBER_RADIO',
      type: 0,
    },
  ],
  createTime: '2023-03-10 17:29:52',
  fieldQmWKSFB167843830585501: '005',
  fieldlXUGSFB1678437737540: '是',
  fieldKknDhEB1678166837506: '2023-03-10',
  updateTime: '2023-03-10 17:29:52',
  id: '1634124401697882112',
  fieldYgHKSFB167843826480601: '003',
  fieldeCtDhEB1678166852263: [
    {
      fieldXgKUSFB1678439679788: 'tuhao01',
      fieldPyBRSFB1678439234351: 'TE17177',
      fieldvqWUSFB1678439712061: 'pici01',
      fieldrCYPSFB1678439013073: 'TE17177',
      fieldvDkSSFB1678439466498: '123',
      fieldCwsSSFB1678439490386: '123',
      fieldFDzUSFB1678439789033: 'tuopanlingjianhao01',
      fieldyPQRSFB1678439272553: '12',
      fieldcuHRSFB1678439250186: '2023-03-08',
      fieldIDgTSFB1678439596204: 'tuopan01',
      fieldcXYPSFB1678439013433: '',
      fieldpIYPSFB1678439012491: 'AH16040(Ⅱ)',
      fieldWvXPSFB1678439011906: '搭焊法兰* *AH6025(A)*SUS304*2017045551-001',
      fieldaCYPSFB1678439012897: '',
      fieldKDZTSFB1678439577508: '1',
      fieldmoZSSFB1678439438746: '无',
      fieldmNYPSFB1678439013273: '12',
      fieldygrOSFB1678438925179: '',
      fieldgEYPSFB1678439012707: '',
      fieldTBrUSFB1678439767198: '2',
      fieldHItTSFB1678439632289: '1',
      fieldCfQUSFB1678439695284: 'guige01',
      fieldfLGVSFB1678439816341: 'qingliao01',
      fieldFkNUSFB1678439687269: 'caizhi01',
      fieldNYYPSFB1678439013618: '',
      fieldFkSQSFB1678439138948: '2',
      fieldgAgOSFB1678438901921: '2017045551-001',
      fieldwNTUSFB1678439702246: '1',
      fieldKMhNSFB167843875651801: '004',
      fieldecpOSFB1678438918981: 'Z-3-A-OW-448',
      fieldOVFUSFB1678439665509: 'mingcheng01',
      fieldGzKPSFB1678438977514: '2017045551-001*搭焊法兰*Z-2-D-DI-041*PF56833',
      fieldCOZUSFB1678439719179: 'bumen01',
      fieldssfQSFB1678439174063: '',
      fieldIbkUSFB1678439749381: '2023-03-07',
    },
    {
      fieldXgKUSFB1678439679788: 'tuhao02',
      fieldPyBRSFB1678439234351: 'TE17180',
      fieldvqWUSFB1678439712061: 'pici02',
      fieldrCYPSFB1678439013073: 'TE17179',
      fieldvDkSSFB1678439466498: '123',
      fieldCwsSSFB1678439490386: '124',
      fieldFDzUSFB1678439789033: 'tuopan02',
      fieldyPQRSFB1678439272553: '1',
      fieldcuHRSFB1678439250186: '2023-03-06',
      fieldIDgTSFB1678439596204: 'tuopan002',
      fieldcXYPSFB1678439013433: '',
      fieldpIYPSFB1678439012491: 'AH16040',
      fieldWvXPSFB1678439011906: '搭焊法兰* *AH6025(A)*SUS304*2017045551-003',
      fieldaCYPSFB1678439012897: '',
      fieldKDZTSFB1678439577508: '2',
      fieldmoZSSFB1678439438746: '3',
      fieldmNYPSFB1678439013273: '1',
      fieldygrOSFB1678438925179: '',
      fieldgEYPSFB1678439012707: '',
      fieldTBrUSFB1678439767198: '3',
      fieldHItTSFB1678439632289: '3',
      fieldCfQUSFB1678439695284: 'guige02',
      fieldfLGVSFB1678439816341: 'qingliao02',
      fieldFkNUSFB1678439687269: 'caizhi02',
      fieldNYYPSFB1678439013618: '',
      fieldFkSQSFB1678439138948: '4',
      fieldgAgOSFB1678438901921: '2017045551-002',
      fieldwNTUSFB1678439702246: '2',
      fieldKMhNSFB167843875651801: '004',
      fieldecpOSFB1678438918981: 'Z-3-A-OW-449',
      fieldOVFUSFB1678439665509: 'mingcheng02',
      fieldGzKPSFB1678438977514: '2017045551-001*搭焊法兰*Z-2-D-DI-041*PF56836',
      fieldCOZUSFB1678439719179: 'bumen02',
      fieldssfQSFB1678439174063: null,
      fieldIbkUSFB1678439749381: '2023-03-06',
    },
  ],
}

export const filterLinkData = {
  msg: '操作成功',
  code: 200,
  data: {
    pageNum: 1,
    pageSize: 10,
    totalPage: 1,
    total: 7,
    list: [
      {
        fieldsQLGSFB1678438134927: '001',
        createBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        updateBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        createTime: '2023-03-10 16:49:42',
        updateTime: '2023-03-10 16:49:42',
        customTitle: '001',
        id: '1634114291336478720',
      },
      {
        fieldsQLGSFB1678438134927: '002',
        createBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        updateBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        createTime: '2023-03-10 16:49:45',
        updateTime: '2023-03-10 16:49:45',
        customTitle: '002',
        id: '1634114306909929472',
      },
      {
        fieldsQLGSFB1678438134927: '003',
        createBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        updateBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        createTime: '2023-03-10 16:49:49',
        updateTime: '2023-03-10 16:49:49',
        customTitle: '003',
        id: '1634114324077215744',
      },
      {
        fieldsQLGSFB1678438134927: '004',
        createBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        updateBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        createTime: '2023-03-10 16:49:52',
        updateTime: '2023-03-10 16:49:52',
        customTitle: '004',
        id: '1634114334969823232',
      },
      {
        fieldsQLGSFB1678438134927: '005',
        createBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        updateBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        createTime: '2023-03-10 16:49:55',
        updateTime: '2023-03-10 16:49:55',
        customTitle: '005',
        id: '1634114346327998464',
      },
      {
        fieldsQLGSFB1678438134927: '006',
        createBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        updateBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        createTime: '2023-03-10 16:49:58',
        updateTime: '2023-03-10 16:49:58',
        customTitle: '006',
        id: '1634114358910910464',
      },
      {
        fieldsQLGSFB1678438134927: '007',
        createBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        updateBy: [
          {
            id: '1634027128165412866',
            name: 'admin002',
            typeId: 'MEMBER_RADIO',
            type: 0,
          },
        ],
        createTime: '2023-03-10 16:50:01',
        updateTime: '2023-03-10 16:50:01',
        customTitle: '007',
        id: '1634114370667544576',
      },
    ],
    headList: [
      {
        createBy: null,
        createTime: null,
        updateBy: null,
        updateTime: null,
        id: '-1',
        formId: null,
        formDesignerId: null,
        type: null,
        attrs: null,
        typeId: 'INPUT',
        span: null,
        idField: null,
        foreignId: null,
        keyPlace: null,
        label: '标题',
        name: 'customTitle',
        sortable: null,
        visible: null,
        width: null,
        widthUnit: null,
        outTableFlag: null,
        joinTable: null,
        joinTableName: null,
        joinFromDesignerId: null,
        childrenFlag: null,
        childrenFromDesignerId: null,
        isDeleted: null,
        tenantId: '1631468255705485314',
        appId: '1631472558016991234',
        children: null,
        vModel: 'customTitle',
      },
      {
        createBy: null,
        createTime: null,
        updateBy: null,
        updateTime: null,
        id: '1634114142449610754',
        formId: null,
        formDesignerId: '1634114142348947457',
        type: 0,
        attrs: '',
        typeId: 'INPUT',
        span: 24,
        idField: 0,
        foreignId: 0,
        keyPlace: 0,
        label: '编号',
        name: 'fieldsQLGSFB1678438134927',
        sortable: 0,
        visible: 1,
        width: null,
        widthUnit: '',
        outTableFlag: 0,
        joinTable: 0,
        joinTableName: '',
        joinFromDesignerId: null,
        childrenFlag: 0,
        childrenFromDesignerId: null,
        isDeleted: 0,
        tenantId: '1631468255705485314',
        appId: '1631472558016991234',
        children: null,
        vModel: 'fieldsQLGSFB1678438134927',
      },
      {
        createBy: null,
        createTime: null,
        updateBy: null,
        updateTime: null,
        id: '1634114142453805058',
        formId: null,
        formDesignerId: '1634114142348947457',
        type: 0,
        attrs: '',
        typeId: 'MEMBER_RADIO',
        span: 0,
        idField: 0,
        foreignId: 0,
        keyPlace: 1,
        label: '提交人',
        name: 'createBy',
        sortable: 0,
        visible: 1,
        width: null,
        widthUnit: '',
        outTableFlag: 0,
        joinTable: 0,
        joinTableName: '',
        joinFromDesignerId: null,
        childrenFlag: 0,
        childrenFromDesignerId: null,
        isDeleted: 0,
        tenantId: '1631468255705485314',
        appId: '1631472558016991234',
        children: null,
        vModel: 'createBy',
      },
      {
        createBy: null,
        createTime: null,
        updateBy: null,
        updateTime: null,
        id: '1634114142457999362',
        formId: null,
        formDesignerId: '1634114142348947457',
        type: 0,
        attrs: '',
        typeId: 'MEMBER_RADIO',
        span: 0,
        idField: 0,
        foreignId: 0,
        keyPlace: 2,
        label: '修改人',
        name: 'updateBy',
        sortable: 0,
        visible: 1,
        width: null,
        widthUnit: '',
        outTableFlag: 0,
        joinTable: 0,
        joinTableName: '',
        joinFromDesignerId: null,
        childrenFlag: 0,
        childrenFromDesignerId: null,
        isDeleted: 0,
        tenantId: '1631468255705485314',
        appId: '1631472558016991234',
        children: null,
        vModel: 'updateBy',
      },
      {
        createBy: null,
        createTime: null,
        updateBy: null,
        updateTime: null,
        id: '1634114142457999363',
        formId: null,
        formDesignerId: '1634114142348947457',
        type: 0,
        attrs: '',
        typeId: 'DATE',
        span: 0,
        idField: 0,
        foreignId: 0,
        keyPlace: 3,
        label: '创建时间',
        name: 'createTime',
        sortable: 0,
        visible: 1,
        width: null,
        widthUnit: '',
        outTableFlag: 0,
        joinTable: 0,
        joinTableName: '',
        joinFromDesignerId: null,
        childrenFlag: 0,
        childrenFromDesignerId: null,
        isDeleted: 0,
        tenantId: '1631468255705485314',
        appId: '1631472558016991234',
        children: null,
        vModel: 'createTime',
      },
      {
        createBy: null,
        createTime: null,
        updateBy: null,
        updateTime: null,
        id: '1634114142462193666',
        formId: null,
        formDesignerId: '1634114142348947457',
        type: 0,
        attrs: '',
        typeId: 'DATE',
        span: 0,
        idField: 0,
        foreignId: 0,
        keyPlace: 4,
        label: '修改时间',
        name: 'updateTime',
        sortable: 0,
        visible: 1,
        width: null,
        widthUnit: '',
        outTableFlag: 0,
        joinTable: 0,
        joinTableName: '',
        joinFromDesignerId: null,
        childrenFlag: 0,
        childrenFromDesignerId: null,
        isDeleted: 0,
        tenantId: '1631468255705485314',
        appId: '1631472558016991234',
        children: null,
        vModel: 'updateTime',
      },
    ],
  },
}
